# Generated by Django 5.0.13 on 2025-11-20 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collection_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='residue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.residue'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ATRIBUIDA', 'Atribuída'), ('EM_ROTA', 'Em Rota'), ('COLETADA', 'Coletada'), ('ENTREGUE_RECICLADORA', 'Entregue na Recicladora'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='residue',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_SOLICITACAO_DE_COLETA', 'Aguardando Solicitação de Coleta'), ('COLETA_SOLICITADA', 'Coleta Solicitada'), ('FINALIZADO', 'Finalizado')], default='AGUARDANDO_SOLICITACAO_DE_COLETA', max_length=50),
        ),
    ]
