# Generated by Django 5.0.13 on 2025-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_created_at_collection_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ATRIBUIDA', 'Atribuída'), ('EM_ROTA', 'Em Rota'), ('COLETADA', 'Coletada'), ('ENTREGUE_RECICLADORA', 'Entregue na Recicladora'), ('PROCESSADO', 'Processado'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='residue',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_SOLICITACAO_DE_COLETA', 'Aguardando Solicitação de Coleta'), ('COLETA_SOLICITADA', 'Coleta Solicitada'), ('PROCESSADO', 'Processado')], default='AGUARDANDO_SOLICITACAO_DE_COLETA', max_length=50),
        ),
    ]
